POST http://localhost:3001/api/plans
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MGU5MTZjYzcwMGM4ODEzMGM1YjIwMzAiLCJpYXQiOjE2MjU4ODg0ODF9.x0G8Sz2d_jlVW_BR9enOiZl_07kk0-K5Cj_vYKrpjeU

{
  "name": "CS Intended Plan",
  "userId": "60e90f328e64a66b1681a339",
  "years": [
    [
      {
        "name": "Fall 2020",
        "courses": [
          {
            "name": "CS 61A",
            "units": "4"
          },
          {
            "name": "EECS 16A",
            "units": "4"
          },
          {
            "name": "GERMAN R5A",
            "units": "4"
          },
          {
            "name": "ESPM 50AC",
            "units": "4"
          }
        ]
      },
      {
        "name": "Spring 2021",
        "courses": [
          {
            "name": "CS 61B",
            "units": "4"
          },
          {
            "name": "EECS 16B",
            "units": "4"
          },
          {
            "name": "GERMAN R5B",
            "units": "4"
          },
          {
            "name": "PSYCH C126",
            "units": "3"
          }
        ]
      },
      {
        "name": "Summer 2021",
        "courses": [
          {
            "name": "DATA C8",
            "units": "4"
          },
          {
            "name": "CS W169A",
            "units": "3"
          }
        ]
      }
    ]
  ]
}