PUT http://localhost:3001/api/plans/60e91a400adb5b4d45213868
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MGU5MWExOTBhZGI1YjRkNDUyMTM4NjIiLCJpYXQiOjE2MjU4ODkzMjV9.g8k1hmjjy5qzPYyNuMChOdhU5JPpx_T2cXHKzIEGQds

{
  "user": "60e90f328e64a66b1681a339",
  "years": [
    [
      {
        "name": "Fall 2020",
        "courses": [
          {
            "name": "CS 61A",
            "units": "4"
          },
          {
            "name": "EECS 16A",
            "units": "4"
          },
          {
            "name": "GERMAN R5A",
            "units": "4"
          },
          {
            "name": "ESPM 50AC",
            "units": "4"
          }
        ]
      },
      {
        "name": "Spring 2021",
        "courses": [
          {
            "name": "CS 61B",
            "units": "4"
          },
          {
            "name": "EECS 16B",
            "units": "4"
          },
          {
            "name": "GERMAN R5B",
            "units": "4"
          }
        ]
      },
      {
        "name": "Summer 2021",
        "courses": [
          {
            "name": "DATA C8",
            "units": "4"
          },
          {
            "name": "CS W169A",
            "units": "3"
          }
        ]
      }
    ]
  ]
}