DELETE http://localhost:3001/api/plans/60e91a400adb5b4d45213868
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MGU5MWExOTBhZGI1YjRkNDUyMTM4NjIiLCJpYXQiOjE2MjU4ODkzMjV9.g8k1hmjjy5qzPYyNuMChOdhU5JPpx_T2cXHKzIEGQds